<?php
$quiz = Session::get('current_quiz');
$parent = Session::get('parent_topic');
$subtopic = Session::get('current_subtopic');

// Professional fallbacks for high-density rendering
$desc = $quiz['desc'] ?? "Challenge yourself with these intriguing queries. Each question sheds light on a different aspect of this domain, honing your beginner skills and paving the way to grasp more complex concepts.";
$tags = (isset($quiz['tags']) && is_array($quiz['tags'])) ? $quiz['tags'] : [$parent['title'] ?? 'Cybersecurity', $subtopic['title'] ?? 'Networking'];
$difficulty = $quiz['difficulty'] ?? 'normal';
$points = $quiz['points_per_correct'] ?? 25;
$totalRewards = $points * 5;
?>

<div class="quiz-evaluation-view fade-in lab-header-section">
    <!-- 1. Background Layer -->
    <div class="evaluation-bg"></div>

    <!-- 2. Header Section (Title, Desc, Tags, Stats) -->
    <div class=" d-flex flex-column align-items-center">
        <!-- Narrative Block -->
        <div class="col-md-8 col-xl-8 text-center mb-3">
            <h3 class="fw-bold mb-2 text-body-emphasis"><?= $quiz['title'] ?></h3>
            <p class="small text-body-secondary lh-base mb-0 opacity-75">
                <?= $desc ?>
            </p>
        </div>

        <!-- Tags Block -->
        <div class="col-12 text-center mb-3">
            <div class="d-flex flex-wrap justify-content-center gap-2">
                <?php foreach ($tags as $tag): ?>
                    <span class="badge badge-evaluation-tag px-3 py-2 rounded-pill"><?= strtolower($tag) ?></span>
                <?php endforeach; ?>
                <button class="btn btn-link text-body-secondary p-0 ms-1" title="Share Quiz"><i class="bx bx-share-alt small"></i></button>
            </div>
        </div>

        <!-- Stats Block -->
        <div class="col-12 text-center">
            <div class="d-flex flex-wrap justify-content-center align-items-center gap-4 py-3 evaluation-stats-bar border-top border-secondary border-opacity-10">
                <div class="stat-group d-flex align-items-center">
                    <span class="text-body-secondary x-small me-3">Difficulty</span>
                    <span class="badge <?= $difficulty == 'hard' ? 'bg-danger' : ($difficulty == 'easy' ? 'bg-info' : 'bg-success') ?> bg-opacity-25 <?= $difficulty == 'hard' ? 'text-danger' : ($difficulty == 'easy' ? 'text-info' : 'text-success') ?> border border-opacity-25 px-3 py-1 rounded-pill x-small fw-bold">
                        <?= strtoupper($difficulty) ?>
                    </span>
                </div>
                <div class="vr bg-secondary opacity-10 d-none d-md-block" style="height: 20px;"></div>
                <div class="stat-group d-flex align-items-center">
                    <span class="text-body-secondary x-small me-3">Rewards Available</span>
                    <span class="text-body-emphasis fw-bold me-2"><?= $totalRewards ?> <i class="bx bxs-hot text-danger"></i></span>
                    <span class="text-body-emphasis fw-bold">2 <i class="bx bxs-zap text-warning"></i></span>
                </div>
                <div class="vr bg-secondary opacity-10 d-none d-md-block" style="height: 20px;"></div>
                <div class="stat-group d-flex align-items-center">
                    <span class="text-body-secondary x-small me-3">Time Remaining</span>
                    <span class="text-body-emphasis fw-bold">06:00 <i class="bx bx-time-five text-body-secondary ms-1"></i></span>
                </div>
            </div>
        </div>
    </div>

    <!-- 3. Interactive Area Section -->
    <div class="container-fluid px-0 mb-3 pb-3">
        <div class="glass-card p-4 p-lg-5 py-xl-5 mt-4">
            <div class="row justify-content-center">
                <div class="col-lg-10">
                    
                    <!-- Progress Steps (Dynamic) -->
                    <div id="evaluation-progress-container" class="evaluation-progress-steps d-flex justify-content-between align-items-center mb-3 position-relative" style="min-height: 40px;">
                        <!-- Generated by JS -->
                    </div>

                    <!-- 1. Start View -->
                    <div id="quiz-start-view" class="quiz-step-view text-center py-5">
                        <button class="btn btn-success rounded-pill px-5 py-3 fw-bold shadow-lg transition-all" onclick="startQuiz()">
                            Begin Quiz <i class="bx bx-play-circle ms-2"></i>
                        </button>
                    </div>

                    <!-- 2. Question View -->
                    <div id="quiz-question-view" class="quiz-step-view d-none">
                        <h4 id="question-text" class="text-center text-body-emphasis mb-5 fw-bold px-md-5"></h4>
                        
                        <div class="row g-4 mb-5">
                            <div class="col-md-6">
                                <button class="btn quiz-option-btn w-100 p-4 text-center h-100" onclick="selectOption(0)">
                                    <span class="option-text"></span>
                                </button>
                            </div>
                            <div class="col-md-6">
                                <button class="btn quiz-option-btn w-100 p-4 text-center h-100" onclick="selectOption(1)">
                                    <span class="option-text"></span>
                                </button>
                            </div>
                            <div class="col-md-6">
                                <button class="btn quiz-option-btn w-100 p-4 text-center h-100" onclick="selectOption(2)">
                                    <span class="option-text"></span>
                                </button>
                            </div>
                            <div class="col-md-6">
                                <button class="btn quiz-option-btn w-100 p-4 text-center h-100" onclick="selectOption(3)">
                                    <span class="option-text"></span>
                                </button>
                            </div>
                        </div>

                        <div class="d-flex justify-content-center gap-3" style="min-height: 50px;">
                            <button id="submit-btn" class="btn btn-success rounded-pill px-5 py-2 fw-bold d-none shadow-sm" onclick="submitAnswer()">Submit Answer</button>
                            <button id="next-btn" class="btn btn-success rounded-pill px-5 py-2 fw-bold d-none shadow-sm" onclick="nextQuestion()">Next Question</button>
                            <button id="result-btn" class="btn btn-primary rounded-pill px-5 py-2 fw-bold d-none shadow-sm" onclick="showResult()">See Result</button>
                        </div>
                    </div>

                    <!-- 3. Result View -->
                    <div id="quiz-result-view" class="quiz-step-view d-none text-center py-5">
                        <div class="result-circle mx-auto mb-2">
                            <div class="result-score"><span id="score-val">0</span>/5</div>
                        </div>
                        <h3 class="text-body-emphasis fw-bold mb-4">Evaluation Complete!</h3>
                        <p id="result-msg" class="text-body-secondary mb-3"></p>
                        <div class="d-flex justify-content-center gap-3">
                            <button class="btn btn-success rounded-pill px-5 py-2 fw-bold transition-all" onclick="location.reload()">Retake Quiz</button>
                            <a href="/quiz" class="btn btn-outline-secondary rounded-pill px-5 py-2 fw-bold">Back to Hub</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<?php
// Assets are now bundled into app.js/app.css
?>

<script>
window.QuizEngineConfig = {
    quizData: <?= json_encode($quizData) ?>,
    pointsPerCorrect: <?= $pointsPerCorrect ?>
};

/**
 * Quiz Engine Module (Restored to Template for Stability)
 * Handles dynamic question loading, state management, and scoring
 */

let currentStep = 0;
let selectedOption = null;
let score = 0;

/**
 * Initialize Dynamic Progress Bar
 */
function initProgressBar() {
    if (!window.QuizEngineConfig || !window.QuizEngineConfig.quizData) return;
    const quizData = window.QuizEngineConfig.quizData;
    const container = document.getElementById('evaluation-progress-container');
    if (!container) return;
    container.innerHTML = '';
    
    quizData.forEach((_, idx) => {
        const step = document.createElement('div');
        step.className = 'step-item' + (idx === 0 ? ' active' : '');
        step.setAttribute('data-step', idx + 1);
        step.innerHTML = `<span>${idx + 1}</span>`;
        container.appendChild(step);
        
        if (idx < quizData.length - 1) {
            const segment = document.createElement('div');
            segment.className = 'progress-segment';
            segment.setAttribute('data-segment', idx + 1);
            container.appendChild(segment);
        }
    });
}

/**
 * Unified Button Management
 */
function toggleButton(id, show) {
    const btn = document.getElementById(id);
    if (!btn) return;
    if (show) {
        btn.classList.remove('d-none');
        btn.style.setProperty('display', 'inline-block', 'important');
    } else {
        btn.classList.add('d-none');
        btn.style.setProperty('display', 'none', 'important');
    }
}

function resetButtons() {
    toggleButton('submit-btn', false);
    toggleButton('next-btn', false);
    toggleButton('result-btn', false);
}

window.startQuiz = function() {
    console.log("[Quiz Engine] Starting Quiz...");
    const startView = document.getElementById('quiz-start-view');
    const questionView = document.getElementById('quiz-question-view');
    
    if (!startView || !questionView) {
        console.error("[Quiz Engine] UI Views not found!");
        return;
    }

    startView.classList.add('d-none');
    questionView.classList.remove('d-none');
    loadQuestion();
};

function loadQuestion() {
    if (!window.QuizEngineConfig || !window.QuizEngineConfig.quizData) {
        console.error("[Quiz Engine] Quiz data missing!");
        return;
    }
    const quizData = window.QuizEngineConfig.quizData;
    const q = quizData[currentStep];
    const qText = document.getElementById('question-text');
    if (qText) qText.innerText = q.text;

    const btns = document.querySelectorAll('.quiz-option-btn');
    btns.forEach((btn, idx) => {
        const optText = btn.querySelector('.option-text');
        if (optText) optText.innerText = q.options[idx];
        btn.classList.remove('correct', 'wrong', 'selected');
        btn.disabled = false;
    });
    
    resetButtons();
    selectedOption = null;
    
    const steps = document.querySelectorAll('.step-item');
    steps.forEach((step, idx) => {
        if(idx === currentStep) step.classList.add('active');
        else if(idx > currentStep) step.classList.remove('active', 'completed-correct', 'completed-wrong');
    });
}

window.selectOption = function(idx) {
    selectedOption = idx;
    const btns = document.querySelectorAll('.quiz-option-btn');
    btns.forEach((btn, i) => {
        if(i === idx) btn.classList.add('selected');
        else btn.classList.remove('selected');
    });
    toggleButton('submit-btn', true);
};

window.submitAnswer = function() {
    if (!window.QuizEngineConfig || !window.QuizEngineConfig.quizData) return;
    const quizData = window.QuizEngineConfig.quizData;
    const q = quizData[currentStep];
    const btns = document.querySelectorAll('.quiz-option-btn');
    const steps = document.querySelectorAll('.step-item');
    const segments = document.querySelectorAll('.progress-segment');
    const currentStepItem = steps[currentStep];
    
    btns.forEach(btn => btn.disabled = true);
    resetButtons();

    let isCorrect = selectedOption === q.correct;
    if(isCorrect) {
        btns[selectedOption].classList.add('correct');
        currentStepItem.classList.add('completed-correct');
        score++;
        if (segments[currentStep]) segments[currentStep].classList.add('correct');
    } else {
        btns[selectedOption].classList.add('wrong');
        currentStepItem.classList.add('completed-wrong');
        if (segments[currentStep]) segments[currentStep].classList.add('wrong');
    }

    const isLastQuestion = (currentStep >= quizData.length - 1);
    if (isLastQuestion) toggleButton('result-btn', true);
    else toggleButton('next-btn', true);
};

window.nextQuestion = function() {
    currentStep++;
    loadQuestion();
};

window.showResult = function() {
    if (!window.QuizEngineConfig || !window.QuizEngineConfig.quizData) return;
    const quizData = window.QuizEngineConfig.quizData;
    const pointsPerCorrect = window.QuizEngineConfig.pointsPerCorrect;

    const qView = document.getElementById('quiz-question-view');
    const rView = document.getElementById('quiz-result-view');
    if (qView) qView.classList.add('d-none');
    if (rView) rView.classList.remove('d-none');
    
    const resultScoreContainer = document.querySelector('.result-score');
    if (resultScoreContainer) {
        resultScoreContainer.innerHTML = `<span id="score-val">${score}</span>/${quizData.length}`;
    }
    
    const totalPoints = score * pointsPerCorrect;
    const ratio = score / quizData.length;
    let msg = "";
    if(ratio === 1) msg = `Priceless! 💎 You earned ${totalPoints} Zeal 🔥. Perfect command!`;
    else if(ratio >= 0.6) msg = `Great job! ⚡️ You earned ${totalPoints} Zeal 🔥. Solid grasp!`;
    else msg = `Keep learning! 🔥 You earned ${totalPoints} Zeal 🔥. Practice makes perfect.`;
    
    const resultMsg = document.getElementById('result-msg');
    if (resultMsg) resultMsg.innerText = msg;
};

document.addEventListener('DOMContentLoaded', initProgressBar);
</script>
