<?php
/**
 * SSLManager - Manages SSL certificate data from Traefik's ACME storage.
 * 
 * Reads the acme.json file generated by Traefik's certificate resolver
 * and provides methods to query, filter, and troubleshoot SSL certificates
 * for user domains.
 */
class SSLManager {
    private $db;
    private $acmePath;
    private $cacheTTL = 900; // 15 minutes in seconds
    private $cacheKey = 'ssl_manager_certs';
    
    public function __construct() {
        $this->db = DatabaseConnection::getClient()->selectDatabase('tom_labs_db');
        
        // Try production path first, then local dev fallback
        $prodPath = '/var/www/traefik-conf/acme.json';
        $localPath = realpath(__DIR__ . '/../../../../traefik-conf/acme.json');
        
        if (file_exists($prodPath) && filesize($prodPath) > 0) {
            $this->acmePath = $prodPath;
        } elseif ($localPath && file_exists($localPath) && filesize($localPath) > 0) {
            $this->acmePath = $localPath;
        } else {
            $this->acmePath = null;
        }
    }
    
    /**
     * Get all SSL certificates visible to the current user.
     * Filters certificates by matching SANs against the user's registered domains
     * and their deployed lab domains.
     *
     * @param string $userId The user's ID
     * @return array Array of certificate objects
     */
    public function getCertificates($userId) {
        // Check cache first
        $cached = $this->getFromCache();
        if ($cached !== false) {
            return $this->filterCertsForUser($cached, $userId);
        }
        
        $allCerts = $this->parseAcmeJson();
        
        if (empty($allCerts)) {
            // Fallback: generate mock data from user's actual domains
            $allCerts = $this->generateDevCertificates($userId);
        }
        
        // Cache the raw certificates
        $this->setCache($allCerts);
        
        return $this->filterCertsForUser($allCerts, $userId);
    }
    
    /**
     * Force refresh: flush cache and re-read acme.json
     *
     * @param string $userId The user's ID
     * @return array Fresh certificate data
     */
    public function refreshCertificates($userId) {
        $this->clearCache();
        return $this->getCertificates($userId);
    }
    
    /**
     * Troubleshoot a specific certificate by verifying DNS for all its SANs.
     *
     * @param string $mainDomain The main domain (CN) of the certificate
     * @param string $userId The user's ID
     * @return array Troubleshoot results for each SAN
     */
    public function troubleshootCertificate($mainDomain, $userId) {
        $certs = $this->getCertificates($userId);
        $targetCert = null;
        
        foreach ($certs as $cert) {
            if ($cert['main_domain'] === $mainDomain) {
                $targetCert = $cert;
                break;
            }
        }
        
        if (!$targetCert) {
            return ['error' => 'Certificate not found'];
        }
        
        $dm = new DomainManager();
        $serverIP = $dm->getServerIP();
        $results = [];
        $issuesFound = 0;
        
        foreach ($targetCert['sans'] as $san) {
            $result = $this->verifySingleDomain($san, $serverIP);
            $results[] = $result;
            if ($result['status'] !== 'ok') {
                $issuesFound++;
            }
        }
        
        return [
            'main_domain' => $mainDomain,
            'resolver' => $targetCert['resolver'],
            'issued' => $targetCert['issued'],
            'expires' => $targetCert['expires'],
            'used_by' => $targetCert['used_by'] ?? null,
            'total_sans' => count($results),
            'issues_found' => $issuesFound,
            'domains' => $results
        ];
    }
    
    /**
     * Verify a single domain's DNS configuration.
     *
     * @param string $domain The domain to verify
     * @param string $expectedIP The expected server IP
     * @return array Verification result
     */
    private function verifySingleDomain($domain, $expectedIP) {
        $result = [
            'domain' => $domain,
            'points_to' => null,
            'expected' => $expectedIP,
            'status' => 'unknown',
            'renewal' => 'unknown',
            'issues' => []
        ];
        
        // Resolve the domain
        $ip = @gethostbyname($domain);
        
        if ($ip === $domain) {
            // DNS lookup failed entirely
            $result['status'] = 'error';
            $result['points_to'] = 'NXDOMAIN';
            $result['renewal'] = 'failed';
            $result['issues'][] = 'DNS record does not exist. Domain may not be configured.';
            return $result;
        }
        
        $result['points_to'] = $ip;
        
        if ($ip === $expectedIP) {
            $result['status'] = 'ok';
            
            // Determine renewal type
            // Check if this is an auto-managed domain (DNS challenge) or HTTP challenge
            $dm = new DomainManager();
            $isDnsChallenge = $dm->checkARecord($domain);
            $result['renewal'] = $isDnsChallenge ? 'auto (DNS)' : 'renewable';
        } else {
            $result['status'] = 'warning';
            $result['renewal'] = 'at risk';
            $result['issues'][] = "Domain points to $ip instead of expected $expectedIP.";
        }
        
        // Check if HTTPS is accessible
        $sslInfo = $this->checkSSLConnection($domain);
        if ($sslInfo) {
            if (isset($sslInfo['error'])) {
                $result['issues'][] = $sslInfo['error'];
                if ($result['status'] === 'ok') {
                    $result['status'] = 'warning';
                }
            }
        }
        
        return $result;
    }
    
    /**
     * Check SSL connection for a domain.
     *
     * @param string $domain The domain to check
     * @return array|null SSL info or null if check failed
     */
    private function checkSSLConnection($domain) {
        // Validate domain format before connecting
        if (!preg_match('/^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$/', $domain)) {
            return ['error' => 'Invalid domain format'];
        }
        
        $context = stream_context_create([
            'ssl' => [
                'capture_peer_cert' => true,
                'verify_peer' => false,
                'verify_peer_name' => false,
            ]
        ]);
        
        $client = @stream_socket_client(
            "ssl://$domain:443",
            $errno,
            $errstr,
            5, // 5 second timeout
            STREAM_CLIENT_CONNECT,
            $context
        );
        
        if (!$client) {
            return ['error' => "SSL connection failed: $errstr"];
        }
        
        $params = stream_context_get_params($client);
        fclose($client);
        
        if (isset($params['options']['ssl']['peer_certificate'])) {
            $certInfo = openssl_x509_parse($params['options']['ssl']['peer_certificate']);
            return [
                'valid_from' => date('d M Y H:i:s T', $certInfo['validFrom_time_t']),
                'valid_to' => date('d M Y H:i:s T', $certInfo['validTo_time_t']),
                'issuer' => $certInfo['issuer']['O'] ?? 'Unknown',
                'is_expired' => $certInfo['validTo_time_t'] < time()
            ];
        }
        
        return null;
    }
    
    /**
     * Parse Traefik's acme.json file to extract certificate data.
     *
     * @return array Array of parsed certificate objects
     */
    private function parseAcmeJson() {
        if (!$this->acmePath || !file_exists($this->acmePath)) {
            return [];
        }
        
        $raw = @file_get_contents($this->acmePath);
        if (!$raw || strlen($raw) < 10) {
            return [];
        }
        
        $data = json_decode($raw, true);
        if (!$data) {
            return [];
        }
        
        $certs = [];
        
        // Traefik acme.json structure:
        // { "resolverName": { "Account": {...}, "Certificates": [{...}] } }
        foreach ($data as $resolverName => $resolverData) {
            $certificates = $resolverData['Certificates'] ?? [];
            
            foreach ($certificates as $certEntry) {
                $certDomain = $certEntry['domain'] ?? [];
                $mainDomain = $certDomain['main'] ?? 'unknown';
                $sans = $certDomain['sans'] ?? [];
                
                // Add main domain to SANs if not already present
                if (!in_array($mainDomain, $sans)) {
                    array_unshift($sans, $mainDomain);
                }
                
                // Decode the certificate to get dates
                $certPEM = $certEntry['certificate'] ?? null;
                $issued = null;
                $expires = null;
                $expiresTimestamp = null;
                
                if ($certPEM) {
                    $decoded = base64_decode($certPEM);
                    if ($decoded) {
                        $certInfo = @openssl_x509_parse($decoded);
                        if ($certInfo) {
                            $issued = date('d M Y H:i:s T', $certInfo['validFrom_time_t']);
                            $expires = date('d M Y H:i:s T', $certInfo['validTo_time_t']);
                            $expiresTimestamp = $certInfo['validTo_time_t'];
                        }
                    }
                }
                
                $daysLeft = null;
                if ($expiresTimestamp) {
                    $daysLeft = max(0, (int)ceil(($expiresTimestamp - time()) / 86400));
                }
                
                $certs[] = [
                    'main_domain' => $mainDomain,
                    'sans' => $sans,
                    'resolver' => $resolverName,
                    'issued' => $issued,
                    'expires' => $expires,
                    'expires_timestamp' => $expiresTimestamp,
                    'days_left' => $daysLeft,
                    'is_expired' => $expiresTimestamp ? ($expiresTimestamp < time()) : null,
                    'is_valid' => $expiresTimestamp ? ($expiresTimestamp > time()) : null,
                    'used_by' => null // Will be populated later
                ];
            }
        }
        
        return $certs;
    }
    
    /**
     * Generate realistic mock certificate data from the user's actual domains.
     * Used in development when acme.json is empty.
     *
     * @param string $userId The user's ID
     * @return array Mock certificate data
     */
    private function generateDevCertificates($userId) {
        $userDomains = iterator_to_array(
            $this->db->domains->find(['user_id' => $userId])
        );
        
        $dm = new DomainManager();
        $usageMap = $dm->getDomainUsageMap($userId);
        
        // Also get domains from deployed labs
        $deployedLabs = iterator_to_array(
            $this->db->deployed_labs->find(['user_id' => (int)$userId])
        );
        
        // Collect all unique domains
        $allDomains = [];
        foreach ($userDomains as $d) {
            $allDomains[] = $d['domain'];
        }
        foreach ($usageMap as $domain => $info) {
            if (!in_array($domain, $allDomains)) {
                $allDomains[] = $domain;
            }
        }
        
        if (empty($allDomains)) {
            return [];
        }
        
        // Group domains by their base (e.g., *.selfmade.fun group)
        $groups = [];
        foreach ($allDomains as $domain) {
            $parts = explode('.', $domain);
            // Use last two parts as group key (e.g., selfmade.fun)
            if (count($parts) >= 2) {
                $baseKey = implode('.', array_slice($parts, -2));
            } else {
                $baseKey = $domain;
            }
            $groups[$baseKey][] = $domain;
        }
        
        $certs = [];
        $certIndex = 0;
        foreach ($groups as $baseKey => $groupDomains) {
            // Create varying expiry dates for realism
            $offsets = [47, 70, 89];
            $daysLeft = $offsets[$certIndex % count($offsets)];
            $issuedTimestamp = time() - (90 - $daysLeft) * 86400;
            $expiresTimestamp = time() + ($daysLeft * 86400);
            
            // Determine which lab uses this cert
            $usedByInfo = null;
            foreach ($groupDomains as $gd) {
                if (isset($usageMap[$gd])) {
                    $usedByInfo = $usageMap[$gd];
                    break;
                }
            }
            
            // Find the "most representative" domain as main
            $mainDomain = $groupDomains[0];
            foreach ($groupDomains as $gd) {
                // Prefer domains without subdomain prefix
                if (substr_count($gd, '.') <= 1) {
                    $mainDomain = $gd;
                    break;
                }
            }
            
            // Build the used_by string
            $usedByStr = null;
            if ($usedByInfo) {
                $usedByStr = $usedByInfo['usage'] . ' (' . $usedByInfo['lab_type'] . ' lab, instance ' . substr($usedByInfo['instance_hash'], 0, 20) . '...)';
            }
            
            // Create badge labels from usage
            $badges = ['selfmade'];
            $badges[] = 'valid';
            if ($usedByInfo) {
                $badges[] = 'in use - ' . $usedByInfo['lab_type'];
            }
            
            $certs[] = [
                'main_domain' => $mainDomain,
                'sans' => $groupDomains,
                'resolver' => 'custom_resolver',
                'issued' => date('d M Y H:i:s T', $issuedTimestamp),
                'expires' => date('d M Y H:i:s T', $expiresTimestamp),
                'expires_timestamp' => $expiresTimestamp,
                'days_left' => $daysLeft,
                'is_expired' => false,
                'is_valid' => true,
                'used_by' => $usedByStr,
                'badges' => $badges
            ];
            
            $certIndex++;
        }
        
        return $certs;
    }
    
    /**
     * Filter certificates to only show those relevant to a user.
     *
     * @param array $allCerts All parsed certificates
     * @param string $userId The user's ID
     * @return array Filtered certificates
     */
    private function filterCertsForUser($allCerts, $userId) {
        // Get all user domains
        $userDomains = [];
        $cursor = $this->db->domains->find(['user_id' => $userId]);
        foreach ($cursor as $d) {
            $userDomains[] = $d['domain'];
        }
        
        // Also get domains from deployed labs
        $dm = new DomainManager();
        $usageMap = $dm->getDomainUsageMap($userId);
        foreach ($usageMap as $domain => $info) {
            if (!in_array($domain, $userDomains)) {
                $userDomains[] = $domain;
            }
        }
        
        if (empty($userDomains)) {
            return $allCerts; // If we can't determine user domains, show all (dev mode)
        }
        
        // Filter: only certs where at least one SAN matches a user domain
        $filtered = [];
        foreach ($allCerts as $cert) {
            $matchFound = false;
            foreach ($cert['sans'] as $san) {
                if (in_array($san, $userDomains)) {
                    $matchFound = true;
                    break;
                }
                // Also check wildcard matches
                foreach ($userDomains as $ud) {
                    if ($this->wildcardMatch($san, $ud)) {
                        $matchFound = true;
                        break 2;
                    }
                }
            }
            if ($matchFound) {
                // Enrich with usage info
                if (!isset($cert['used_by']) || !$cert['used_by']) {
                    foreach ($cert['sans'] as $san) {
                        if (isset($usageMap[$san])) {
                            $info = $usageMap[$san];
                            $cert['used_by'] = $info['usage'] . ' (' . $info['lab_type'] . ' lab, instance ' . substr($info['instance_hash'], 0, 20) . '...)';
                            break;
                        }
                    }
                }
                $filtered[] = $cert;
            }
        }
        
        return $filtered;
    }
    
    /**
     * Check if a wildcard pattern matches a domain.
     *
     * @param string $pattern Wildcard pattern (e.g., *.example.com)
     * @param string $domain Domain to match
     * @return bool
     */
    private function wildcardMatch($pattern, $domain) {
        if (strpos($pattern, '*') === false) {
            return $pattern === $domain;
        }
        $regex = '/^' . str_replace(['.', '*'], ['\.', '[a-zA-Z0-9-]+'], $pattern) . '$/i';
        return (bool) preg_match($regex, $domain);
    }
    
    // ──────────────────────────────────────────────
    // Cache helpers using the existing Cache class
    // ──────────────────────────────────────────────
    
    private function getFromCache() {
        $data = Cache::get($this->cacheKey);
        if (!$data || !is_array($data)) {
            return false;
        }
        // Check TTL
        if (isset($data['_ts']) && (time() - $data['_ts']) > $this->cacheTTL) {
            return false;
        }
        return $data['certs'] ?? false;
    }
    
    private function setCache($certs) {
        try {
            Cache::set($this->cacheKey, [
                '_ts' => time(),
                'certs' => $certs
            ]);
        } catch (Exception $e) {
            // Cache failure is non-fatal
            error_log("SSLManager cache write failed: " . $e->getMessage());
        }
    }
    
    private function clearCache() {
        try {
            // Set with expired timestamp to force refresh
            Cache::set($this->cacheKey, [
                '_ts' => 0,
                'certs' => []
            ]);
        } catch (Exception $e) {
            error_log("SSLManager cache clear failed: " . $e->getMessage());
        }
    }
    
    /**
     * Get count of auto-managed certificates.
     *
     * @param array $certs Certificate array
     * @return int
     */
    public function getAutoManagedCount($certs) {
        $count = 0;
        foreach ($certs as $cert) {
            if (isset($cert['resolver']) && !empty($cert['resolver'])) {
                $count++;
            }
        }
        return $count;
    }
}
