<?php

/**
 * Generated by Exception Generator
 * @branch none
 * @user sathish
 * @date January 3rd, 2026 22:03:43
 */

class ObjectNotSupportedException extends Exception {

    protected $message = "The type of data you supplied is not supported.";
    protected $code = 1001;

    public function __construct() {
        parent::__construct($this->message, $this->code);
    }

    public function __toString() {
        return __CLASS__ . ": [{$this->code}]: {$this->message}\n";
    }

}