<?php

/**
 * Generated by Exception Generator
 * @branch none
 * @user sathish
 * @date January 3rd, 2026 21:57:55
 */

class TemplateUnavailableException extends Exception {

    protected $message = "The requested template file could not be found in the specified directory.";
    protected $code = 1000;

    public function __construct() {
        parent::__construct($this->message, $this->code);
    }

    public function __toString() {
        return __CLASS__ . ": [{$this->code}]: {$this->message}\n";
    }

}