<?php

/**
 * Generated by Exception Generator
 * @branch master
 * @user root
 * @date January 7th, 2026 01:00:54
 */

class UnsupportedDomainException extends Exception {

    protected $message = "The type of data you supplied is not supported.";
    protected $code = 1002;

    public function __construct() {
        parent::__construct($this->message, $this->code);
    }

    public function __toString() {
        return __CLASS__ . ": [{$this->code}]: {$this->message}\n";
    }

}