<?php

/**
 * Generated by Exception Generator
 * @branch master
 * @user root
 * @date January 7th, 2026 01:28:41
 */

class UnsupportedEnvironmentException extends Exception {

    protected $message = "The type of OS is not Support.";
    protected $code = 1003;

    public function __construct() {
        parent::__construct($this->message, $this->code);
    }

    public function __toString() {
        return __CLASS__ . ": [{$this->code}]: {$this->message}\n";
    }

}