const sass = require("sass");
module.exports = function (grunt) {
  grunt.initConfig({
    pkg: grunt.file.readJSON("package.json"),
    concat: {
      options: {
        sourceMap: true,
      },
      dist: {
        src: [
          // No ../ here because the Gruntfile is INSIDE the grunt folder
          "node_modules/@coreui/coreui/dist/js/coreui.bundle.min.js",
          "node_modules/simplebar/dist/simplebar.min.js",
          "node_modules/chart.js/dist/chart.umd.js",
          "node_modules/@coreui/chartjs/dist/js/coreui-chartjs.js",
          "node_modules/@coreui/utils/dist/umd/index.js",
          "node_modules/three/build/three.min.js",

          "../js/*.js",
          "../js/**/*.js",
        ],
        dest: "../../htdocs/js/app.js",
      },
    },

    uglify: {
      options: {
        mangle: false,
        compress: false,
        beautify: false,
      },
      build: {
        files: {
          "../../htdocs/js/app.min.js": ["../../htdocs/js/app.js"],
        },
      },
    },

    obfuscator: {
      options: {
        banner: "",
        debugProtection: true,
        debugProtectionInterval: true,
        controlFlowFlattening: true,
        controlFlowFlatteningThreshold: 1,
        disableConsoleOutput: true,
        mangle: true,
        selfDefending: true,
        domainLock: ["labs.tomweb.fun", "labsbeta.tomweb.fun"],
      },
      build: {
        files: {
          "../../htdocs/js/app.o.js": ["../../htdocs/js/app.js"],
        },
      },
    },

    sass: {
      options: {
        style: "expanded",
        sourceMap: false,
        implementation: sass,
        includePaths: ["node_modules"],
      },
      dist: {
        files: {
          "../../htdocs/css/app.css": "../sass/app.scss",
        },
      },
    },
    copy: {
      main: {
        files: [
          {
            expand: true,
            flatten: true,
            src: ["node_modules/@coreui/icons/sprites/**"],
            dest: "../../htdocs/assets/icons/",
          },
        ],
      },
    },

    watch: {
      options: {
        spawn: false,
        debounceDelay: 300,
        interval: 100, // Very frequent polling for Docker responsiveness
      },
      scripts: {
        files: [
          "Gruntfile.js",
          "../js/**/*.js",
        ],
        tasks: ["concat", "secureSourceMaps", "uglify:build", "obfuscator"],
      },
      css: {
        files: [
          "../sass/**/*.scss",
          "../sass/**/*.sass",
        ],
        tasks: ["sass"],
      },
    },
  });

  // Log whenever sass runs to confirm detection
  grunt.registerTask("sass-log", function () {
    grunt.log.writeln(">> Sass change detected, compiling...");
  });

  // Wrap sass dist to include logging
  grunt.registerTask("sass-build", ["sass-log", "sass:dist"]);

  // Update default and watch tasks to use the new build
  grunt.config.set("watch.css.tasks", ["sass-build"]);

  grunt.loadNpmTasks("grunt-contrib-watch");
  grunt.loadNpmTasks("grunt-contrib-concat");
  grunt.loadNpmTasks("grunt-sass");
  grunt.loadNpmTasks("grunt-contrib-uglify");
  grunt.loadNpmTasks("grunt-contrib-obfuscator");
  grunt.loadNpmTasks("grunt-contrib-copy");

  // Custom task to strip vendor source map comments and securely empty sourcesContent from generated maps
  grunt.registerTask(
    "secureSourceMaps",
    "Securely remove source code content from .map files",
    function () {
      const fs = require("fs");
      const jsFiles = ["../../htdocs/js/app.js", "../../htdocs/js/app.min.js"];
      const mapFiles = ["../../htdocs/js/app.js.map", "../../htdocs/js/app.min.js.map"];

      jsFiles.forEach(function (file) {
        try {
          let content = fs.readFileSync(file, "utf8");
          const lines = content.split("\n");
          // Remove vendor source maps but keep the final one generated by grunt concat (app.js.map)
          const cleanedLines = lines.map(function (line) {
            if (line.includes("sourceMappingURL=") && !line.includes("app.js.map") && !line.includes("app.min.js.map")) {
              return "";
            }
            return line;
          });
          fs.writeFileSync(file, cleanedLines.join("\n"), "utf8");
          grunt.log.ok("Cleaned vendor source maps from " + file);
        } catch (err) {
          if (err.code !== "ENOENT") grunt.log.warn("Error processing " + file + ": " + err.message);
        }
      });

      mapFiles.forEach(function (file) {
        try {
          let content = fs.readFileSync(file, "utf8");
          let mapData = JSON.parse(content);
          if (mapData.sourcesContent) {
            delete mapData.sourcesContent; // Secure it by removing actual code
            fs.writeFileSync(file, JSON.stringify(mapData), "utf8");
            grunt.log.ok("Secured source map (removed sourcesContent): " + file);
          }
        } catch (err) {
          if (err.code !== "ENOENT") grunt.log.warn("Error processing map " + file + ": " + err.message);
        }
      });
    },
  );

  grunt.registerTask("default", [
    "copy",
    "sass-build",
    "concat",
    "secureSourceMaps",
    "uglify",
    "watch",
  ]);
  grunt.registerTask("build", [
    "copy",
    "sass:dist",
    "concat",
    "secureSourceMaps",
    "uglify",
    "obfuscator",
  ]);
};
